[gauntlet]
name = 'Brew'
description = """
Manage brew formulae
"""

[[entrypoint]]
id = 'search'
name = 'Search'
path = 'src/search.tsx'
icon = "icon.png"
type = 'view'
description = """
Search brew packages
"""

[[entrypoint]]
id = "plugin-store"
name = "Plugin Store"
path = "src/plugin-store.tsx"
type = "view"
description = "Browse and install plugins"

[[supported_system]]
os = 'macos'

[[supported_system]]
os = 'windows'

[permissions]
environment = ["RUST_LOG", "LD_LIBRARY_PATH"]
system = ["systemMemoryInfo"]
network = ["formulae.brew.sh", "raw.githubusercontent.com", "github.com"]
clipboard = ["read", "write", "clear"]
main_search_bar = ["read"]

[permissions.exec]
command = ["brew"]

[permissions.filesystem]
read = ["{common:plugin-cache}"]
write = ["{common:plugin-cache}"]
