# "$schema" = "https://raw.githubusercontent.com/BennoCrafter/gauntlet/refs/heads/manifest-schema/rust/manifest_schema/schema.json"

[gauntlet]
name = 'Brew'
description = """
Manage brew formulae
"""

[[entrypoint]]
id = 'search'
name = 'Search'
path = 'src/search.tsx'
icon = "icon.png"
type = 'view'
description = """
Search brew packages
"""

[[supported_system]]
os = 'macos'

[permissions]
environment = ["RUST_LOG", "LD_LIBRARY_PATH"]
system = ["systemMemoryInfo"]
network = ["formulae.brew.sh"]
main_search_bar = ["read"]

[permissions.exec]
command = ["brew", "sh"]
executable = ["/opt/homebrew/bin/brew"]

[permissions.filesystem]
read = ["{common:plugin-cache}"]
write = ["{common:plugin-cache}"]
